# CHƯƠNG 2:  MA TRẬN VÀ HỆ PHƯƠNG TRÌNH TUYẾN TÍNH

#### 1. Dẫn nhập – Một số hàm về xử lý vector với Python

- Hàm “scale” 

In [1]:
def scale(a, v):
    return [a*vi for vi in v]
v = [3,5,7]
scale(10, v)

[30, 50, 70]

- Hàm lấy tổng hai vector

In [2]:
def sumvector(v, w):
    return [vi+wi for (vi, wi) in zip(v, w)]
v = [3,5,7]
w = [2,4,6]
sumvector(v, w)

[5, 9, 13]

- Hàm nhân 2 vector vô hướng

In [3]:
def dotvector(v, w):
    return sum([vi*wi for (vi, wi) in zip(v, w)])
dotvector(v, w)

68

- Hàm tính chiều dài một vector

In [4]:
def lenvector(v):
    return dotvector(v,v)
lenvector(w) 

56

#### 2. Bài toán ứng dụng 1 – Phân loại tuyến tính 

In [6]:
import numpy as np
scores = np.array([-1, 1, 2, -3, 5, -4]) 
scores

array([-1,  1,  2, -3,  5, -4])

In [7]:
scores >= 0

array([False,  True,  True, False,  True, False])

In [8]:
scores < 0

array([ True, False, False,  True, False,  True])

In [10]:
np.select([scores >=0, scores < 0],['so duong', 'so am'])

array(['so am', 'so duong', 'so duong', 'so am', 'so duong', 'so am'],
      dtype='<U8')

Kết quả câu lệnh bên trên là phương cách phân loại dữ liệu, theo đó, lệnh select phân thành 2
loại. Ví dụ dưới đây cho ta thấy lệnh np.select có thể phân loại thành 3 loại:

In [11]:
scores = np.array([-1, 1, 2, 0, -3, 5, 0, -4])
np.select([scores >0, scores ==0, scores < 0],['so duong', 'so 0', 'so am']) 

array(['so am', 'so duong', 'so duong', 'so 0', 'so am', 'so duong',
       'so 0', 'so am'], dtype='<U8')

#### 3. Thực hành xử lý ma trận

##### 3.1. Cơ bản về xử lý ma trận

```Thực hành```: Sinh viên thực hiện ôn luyện các lệnh sau: 

In [12]:
import numpy as np
from scipy import linalg, sparse

D = np.mat([ [3,4], [5,6] ])
print(D)

[[3 4]
 [5 6]]


In [16]:
C = np.mat(np.random.random((5,7)))
print(C)

[[0.7619708  0.72914213 0.09723843 0.82832406 0.48242643 0.76021062
  0.96206838]
 [0.646637   0.68705656 0.45399331 0.21715203 0.62516662 0.12090179
  0.40556584]
 [0.96743903 0.83039481 0.91620236 0.05448542 0.95709168 0.36180635
  0.08966411]
 [0.28969101 0.7085536  0.96004107 0.91349556 0.26379591 0.15437255
  0.66019877]
 [0.77861817 0.52901669 0.85656408 0.39797013 0.10189348 0.26800106
  0.44060682]]


In [18]:
A = np.mat(np.random.random((2,2)))
print(A)

[[0.48861275 0.40324496]
 [0.67280677 0.17581448]]


In [21]:
b = np.array([(1+5j, 2j, 3j),(4, 5,
6)])
B = np.asmatrix(b)
print(b)

[[1.+5.j 0.+2.j 0.+3.j]
 [4.+0.j 5.+0.j 6.+0.j]]


In [22]:
print(B)

[[1.+5.j 0.+2.j 0.+3.j]
 [4.+0.j 5.+0.j 6.+0.j]]


In [23]:
A.T

matrix([[0.48861275, 0.67280677],
        [0.40324496, 0.17581448]])

In [24]:
A.I

matrix([[-0.94829435,  2.17499108],
        [ 3.6289324 , -2.63544117]])

In [25]:
linalg.inv(A)

array([[-0.94829435,  2.17499108],
       [ 3.6289324 , -2.63544117]])

In [27]:
M = np.array([[-1,3,2],[0,-
2,1],[1,5,-2]])
M_lower = np.tril(M)
print(M_lower)

[[-1  0  0]
 [ 0 -2  0]
 [ 1  5 -2]]


In [28]:
M = np.array([[-1,3,2],[0,-
2,1],[1,5,-2]])
M_upper = np.triu(M)
print(M_upper)

[[-1  3  2]
 [ 0 -2  1]
 [ 0  0 -2]]


In [29]:
M = np.array([[-1,3,2],[0,-
2,1],[1,5,-2]])
v_diag = np.diag(M) #vector đường chéo 
print (v_diag) 

[-1 -2 -2]


In [30]:
M_diag = np.diag(v_diag)
print (M_diag)

[[-1  0  0]
 [ 0 -2  0]
 [ 0  0 -2]]


**Thực hiện tính toán đơn giản trên ma trận**

**Bài tập dẫn nhập:** Hãy xác định x,y và z để 2 ma trận bằng nhau: 

In [33]:
import sympy as sp

x = sp.Symbol('x')
y = sp.Symbol('y')
z = sp.Symbol('z')
sp.solve([x*x+2-6, y-1-6, x+z-1, 2*x*x-8, z*z+4-5, y-z-8], [x, y, z])

[(2, 7, -1)]

#### 3.2. Các phép biến đổi sơ cấp trên ma trận

In [34]:
import numpy as np 
A = np.reshape(np.arange(36.0), (6,6))
print(A)

[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]
 [24. 25. 26. 27. 28. 29.]
 [30. 31. 32. 33. 34. 35.]]


In [35]:
I6 = np.identity(6)
print(I6)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


Sau đó, xem lại kích thước của ma trận (số lượng phần tử) và in đường chéo của ma trận A: 


In [36]:
A.size

36

In [37]:
np.matrix.diagonal(A)

array([ 0.,  7., 14., 21., 28., 35.])

Thành lập ma trận A  mới bằng công thức A = A + I

In [38]:
A = A + I6
print(A)

[[ 1.  1.  2.  3.  4.  5.]
 [ 6.  8.  8.  9. 10. 11.]
 [12. 13. 15. 15. 16. 17.]
 [18. 19. 20. 22. 22. 23.]
 [24. 25. 26. 27. 29. 29.]
 [30. 31. 32. 33. 34. 36.]]


Tính tích (nhân) ma trận với vector (là dạng ma trận đặc biệt):

In [39]:
vecB = np.array([1., 2., 3., 4., 5., 6.])
C = A.dot(vecB)
print(C) 

[ 71. 198. 325. 452. 579. 706.]


In [40]:
D = np.array([[1., 2., 3., 4., 5., 6.], [1., 0., 1., 0., 1., 0.]])
print(D)

[[1. 2. 3. 4. 5. 6.]
 [1. 0. 1. 0. 1. 0.]]


Tính tích ma trận A và D: A x D

In [51]:
E = A.dot(D) 

ValueError: shapes (6,6) and (2,6) not aligned: 6 (dim 1) != 2 (dim 0)

In [43]:
F = np.array([[1., 1.], [2., 0.], [3., 1.], [4., 0], [5., 1], [6., 0.]])
G = A.dot(F)
print(F)

[[1. 1.]
 [2. 0.]
 [3. 1.]
 [4. 0.]
 [5. 1.]
 [6. 0.]]


In [52]:
print(G)

[[ 71.   7.]
 [198.  24.]
 [325.  43.]
 [452.  60.]
 [579.  79.]
 [706.  96.]]


In [53]:
# Tính ma trận nghịch đảo:
np.linalg.inv(A) 

array([[-0.17525773, -0.30412371, -0.18298969, -0.06185567,  0.05927835,
         0.18041237],
       [-0.27835052,  0.04639175, -0.12886598, -0.05412371,  0.02061856,
         0.09536082],
       [-0.1314433 , -0.10309278,  0.17525773, -0.04639175, -0.01804124,
         0.01030928],
       [ 0.01546392, -0.00257732, -0.02061856,  0.21134021, -0.05670103,
        -0.07474227],
       [ 0.16237113,  0.09793814,  0.03350515, -0.03092784,  0.15463918,
        -0.15979381],
       [ 0.30927835,  0.19845361,  0.08762887, -0.02319588, -0.13402062,
         0.00515464]])

In [54]:
# Câu hỏi: Lệnh sau sẽ trả về kết quả gì?
np.linalg.inv(np.linalg.inv(A))

array([[ 4.,  1.,  2.,  3.,  4.,  5.],
       [ 6., 11.,  8.,  9., 10., 11.],
       [12., 13., 18., 15., 16., 17.],
       [18., 19., 20., 25., 22., 23.],
       [24., 25., 26., 27., 32., 29.],
       [30., 31., 32., 33., 34., 39.]])

#### 4. Bài toán ứng dụng 2 – Tính toán dãy Fibonacci: Con đường tìm đến tỉ số vàng!

In [57]:
import numpy as np
A = np.array( [ [1,1], [1,0] ] )
b = np.array([1, 0])
n = 10
for i in range(n):
    b = A.dot(b)
print(b) 

[89 55]


#### 5. Cơ bản về hệ phương trình tuyến tính và ứng dụng minh họa 

##### 5.2. Bài toán ứng dụng 3 – Đếm số lượng xe vào khu vực trung tâm

In [58]:
import sympy as sp
from sympy import Symbol
17
x1 = Symbol('x1')
x2 = Symbol('x2')
x3 = Symbol('x3')
x4 = Symbol('x4')
from sympy import solve
pt1 = x4+610-450-x1
pt2 = x1+400-x2-640
pt3 = x2+600-x3
pt4 = x3-x4-520
nghiem = sp.solve((pt1, pt2, pt3, pt4))
nghiem

{x1: x4 + 160, x2: x4 - 80, x3: x4 + 520}

In [69]:
# Bài tập: Sinh viên thử bằng phương pháp nhân ma trận:
import numpy as np
A = np.matrix([[-1,0,0,1],[1,-1,0,0],[0,1,-1,0],[0,0,1,-1]])

In [ ]:
A_nghichdao = np.linalg.inv(A)

=> Các hàng không độc lập tuyến tính ⇒ Ma trận suy biến (không nghịch đảo được).

# BÀI TẬP CHƯƠNG 2 

```Câu 1```

- Vấn đề 1 (Problem 1)

In [71]:
import numpy as np

A = np.array([[1, -1],
              [2,  3]])
B = np.array([-2, 6])

x = np.linalg.solve(A, B)
print("Giao điểm:", x)


Giao điểm: [0. 2.]


- Vấn đề 2 (Problem 2)

In [72]:
A = np.array([[ 1, -1,  0],
              [ 2, -1, -1],
              [ 1,  1,  1]])
B = np.array([2, 3, 6])

x = np.linalg.solve(A, B)
print("Giao điểm:", x)


Giao điểm: [3. 1. 2.]


- Vấn đề 3 (Problem 3)

In [73]:
A = np.array([[1, 1, 1],
              [4, 2, 1],
              [9, 3, 1]])
B = np.array([4, 4, 4])

x = np.linalg.solve(A, B)
print("Hệ số đa thức [a, b, c]:", x)


Hệ số đa thức [a, b, c]: [0. 0. 4.]


- Vấn đề 4 (Problem 4)

In [74]:
A = np.array([[1, 0, 1],
              [1, 1, -2],
              [-2, 2, 1]])
B = np.array([1, -3, 0])

x = np.linalg.solve(A, B)
print("Hệ số [a, b, c]:", x)


Hệ số [a, b, c]: [-0.11111111 -0.66666667  1.11111111]


```Câu 2```

In [76]:
# Vấn đề 1
x, y = sp.symbols('x y')

eq1 = sp.Eq(x - y, -2)
eq2 = sp.Eq(2*x + 3*y, 6)

solution = sp.solve((eq1, eq2), (x, y))
print(solution)


{x: 0, y: 2}


In [78]:
# Vấn đề 2
x, y, z = sp.symbols('x y z')

eq1 = sp.Eq(x - y, 2)
eq2 = sp.Eq(2*x - y - z, 3)
eq3 = sp.Eq(x + y + z, 6)

solution = sp.solve((eq1, eq2, eq3), (x, y, z))
print(solution)


{x: 3, y: 1, z: 2}


In [79]:
# Vấn đề 3 
a, b, c = sp.symbols('a b c')

eq1 = sp.Eq(a + b + c, 4)       # p(1)
eq2 = sp.Eq(4*a + 2*b + c, 4)   # p(2)
eq3 = sp.Eq(9*a + 3*b + c, 4)   # p(3)

solution = sp.solve((eq1, eq2, eq3), (a, b, c))
print(solution)


{a: 0, b: 0, c: 4}


In [80]:
# Vấn đề 4 
a, b, c = sp.symbols('a b c')

eq1 = sp.Eq(a + c, 1)
eq2 = sp.Eq(a + b - 2*c, -3)
eq3 = sp.Eq(-2*a + 2*b + c, 0)

solution = sp.solve((eq1, eq2, eq3), (a, b, c))
print(solution)


{a: -1/9, b: -2/3, c: 10/9}


```Câu 3```

In [81]:
import numpy as np

def fibonacci_matrix(k):
    F = np.array([[1, 1],
                  [1, 0]], dtype=object)
    result = np.linalg.matrix_power(F, k)
    return result

# Kiểm tra với k = 5 (F_5)
k = 5
Fk = fibonacci_matrix(k)
print("F_{} =\n{}".format(k, Fk))

# So sánh với Fibonacci thật
def fib(n):
    a, b = 0, 1
    for _ in range(n):
        a, b = b, a + b
    return a

print("Fib(k+1) =", fib(k+1))
print("Fib(k)   =", fib(k))
print("Fib(k-1) =", fib(k-1))


F_5 =
[[8 5]
 [5 3]]
Fib(k+1) = 8
Fib(k)   = 5
Fib(k-1) = 3
