# CHƯƠNG 3: MA TRẬN VÀ HỆ PHƯƠNG TRÌNH TUYẾN TÍNH

### 1. Tóm tắt một số phép xử lý ma trận của NumPy và Scipy 

##### 1.1. Một số phép xử lý ma trận của NumPy và Scipy 

- Khởi tạo ma trận: 

In [9]:
from scipy import linalg # Tải gói linalg của scipy vào bộ nhớ (để sử dụng)
import numpy as np # Tải gói numpy vào sử dụng với tên gọi là np
# [Ôn tập một số lệnh đã học]
a = np.array([1, 2, 3])
b = np.array([(1+9j, 2j, 3j), (4j, 5j, 6j)]) # số phức
c = np.array([[ (0.5, 1.5, 10), (3,2,1) ] , [(6,5,4), (7,8,9)]]) # ma trận số thực
# Các kiểu khai báo và khởi tạo ma trận:
A = np.matrix(np.random.random( (2,2) ) )
B = np.asmatrix(b) # Chuyển b thành dạng ma trận
C = np.mat(np.random.random( (10,5) ) )
D = np.mat([ [4, 3], [2, 6] ])
F = np.eye(3, k=1) # tạo ma trận đường chéo. 3 là ma trận 3x3, k=1 là đường chéo nằm phía trên đường chéo chính (k = 0). 

In [3]:
A

matrix([[0.98818235, 0.32287671],
        [0.80812783, 0.12635926]])

In [4]:
B

matrix([[1.+9.j, 0.+2.j, 0.+3.j],
        [0.+4.j, 0.+5.j, 0.+6.j]])

In [5]:
C

matrix([[8.36581900e-01, 6.35185886e-01, 5.47179015e-02, 9.55055523e-01,
         1.81494271e-01],
        [4.24818167e-01, 8.07150886e-01, 9.72320214e-01, 3.75019925e-01,
         4.87528817e-01],
        [5.01544006e-01, 1.46608181e-01, 1.17151443e-01, 9.00808042e-01,
         5.62607654e-01],
        [8.17682166e-01, 6.80733308e-01, 6.26658230e-02, 9.73425406e-01,
         5.68237027e-02],
        [8.95271869e-05, 9.63945449e-01, 9.28971021e-01, 6.24118085e-01,
         3.97582557e-01],
        [7.05842762e-01, 6.37922335e-01, 3.93422959e-01, 4.18309278e-01,
         6.73805671e-01],
        [5.81755789e-01, 5.83237582e-01, 8.32696893e-01, 3.99618732e-01,
         3.77338002e-01],
        [7.20702163e-01, 1.42142652e-01, 6.90711313e-01, 5.15478407e-01,
         5.14238373e-01],
        [4.06984056e-01, 5.57830405e-01, 2.51359302e-01, 2.71809404e-01,
         3.12409474e-01],
        [7.20910496e-01, 2.56025086e-01, 1.08294832e-01, 6.81044926e-01,
         9.10446480e-01]])

In [6]:
D

matrix([[4, 3],
        [2, 6]])

In [8]:
F

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [11]:
F = np.eye(3, k=0)
F

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
F = np.eye(3, k=-1)
F

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

- Các phép xử lý đơn giản

In [15]:
# Xem hạng ma trận:
np.linalg.matrix_rank(C) 

5

In [16]:
# Tính ma trận nghịch đảo:
A.I 

matrix([[ -4.97488685,  12.2214234 ],
        [ 11.69130534, -23.72649649]])

In [17]:
linalg.inv(A) # đây là lệnh của gói scipy, nên có thể sử dụng scipy.linalg.inv(A) 

array([[ -4.97488685,  12.2214234 ],
       [ 11.69130534, -23.72649649]])

In [18]:
# Định thức ma trận:
linalg.det(A)

-0.04024508094291934

In [19]:
# Chuyển đổi ma trận:
A.T # chuyển vị (dòng <-> cột) 

matrix([[0.95487477, 0.47051753],
        [0.49185217, 0.20021472]])

In [20]:
A.H # chuyển vị liên hợp 

matrix([[0.95487477, 0.47051753],
        [0.49185217, 0.20021472]])

- Giải các loại phương trình tuyến tính: 

In [21]:
linalg.solve(A, b)

array([[-4.97488685  +4.11171192j,  0.         +51.15734328j,
         0.         +58.40387983j],
       [11.69130534 +10.31576211j,  0.         -95.24987175j,
         0.        -107.2850629j ]])

In [23]:
E = np.mat(a).T
E

matrix([[1],
        [2],
        [3]])

In [24]:
linalg.lstsq(F, E)

(array([[0.],
        [1.],
        [2.]]),
 array([], dtype=float64),
 2,
 array([1., 1., 0.]))

- Các hàm trên ma trận 

In [25]:
# Cộng ma trận:
np.add(A, D)

matrix([[4.95487477, 3.49185217],
        [2.47051753, 6.20021472]])

In [26]:
# Trừ ma trận:
np.subtract(A, D) 

matrix([[-3.04512523, -2.50814783],
        [-1.52948247, -5.79978528]])

In [27]:
# Chia ma trận:
np.divide(A, D)

matrix([[0.23871869, 0.16395072],
        [0.23525876, 0.03336912]])

In [28]:
# Nhân ma trận:
A @ D

matrix([[4.80320343, 5.81573736],
        [2.28249957, 2.61284093]])

In [29]:
np.multiply(D, A)

matrix([[3.81949909, 1.47555652],
        [0.94103506, 1.20128834]])

In [30]:
np.dot(A, D)

matrix([[4.80320343, 5.81573736],
        [2.28249957, 2.61284093]])

In [31]:
np.vdot(A, D)

matrix([[3.81949909]])

In [32]:
# Hàm lũy thừa và logarith ma trận:
linalg.expm(A)

array([[2.84010236, 0.93193691],
       [0.89151309, 1.41021024]])

In [33]:
linalg.logm(A)

array([[-0.50817586+0.60135877j,  1.43152123-1.26366824j],
       [ 1.36942738-1.2088552j , -2.70459164+2.54023388j]])

### 2. Tích (nhân) ma trận với ma trận 

##### 2.3. Ma trận hội tụ 

- Ma trận phân kỳ: 

In [34]:
import numpy as np
# Tính ma trận A:
A = np.array([ [0,1], [1,0]])
print(A) 

[[0 1]
 [1 0]]


In [ ]:
temp = A.dot(A)
print(temp) 

[[1 0]
 [0 1]]


In [36]:
k= 6
for i in range(k-1):
   temp = temp.dot(A)
   print (temp)
   print('---')

[[0 1]
 [1 0]]
---
[[1 0]
 [0 1]]
---
[[0 1]
 [1 0]]
---
[[1 0]
 [0 1]]
---
[[0 1]
 [1 0]]
---


In [37]:
# Tính ma trận B:
B = np.array([ [0,-1], [-1,0]])
print(B)

[[ 0 -1]
 [-1  0]]


In [38]:
temp = B.dot(B)
print(temp) 

[[1 0]
 [0 1]]


In [39]:
k= 5
for i in range(k-1):
   temp = temp.dot(B)
   print (temp)
   print('---') 

[[ 0 -1]
 [-1  0]]
---
[[1 0]
 [0 1]]
---
[[ 0 -1]
 [-1  0]]
---
[[1 0]
 [0 1]]
---


- Ma trận hội tụ - Convergent matrix: 

In [5]:
import numpy as np 
C = np.array([ [1, 0, 0], [0, 0.5, 1], [0, 0, 0.5] ])
print(C) 


[[1.  0.  0. ]
 [0.  0.5 1. ]
 [0.  0.  0.5]]


In [6]:
temp = C.dot(C)
print(temp) 

[[1.   0.   0.  ]
 [0.   0.25 1.  ]
 [0.   0.   0.25]]


In [42]:
k= 1000
for i in range(k-1):
    temp = temp.dot(C)
print(temp) 

[[1.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 4.66631809e-302 9.34196882e-299]
 [0.00000000e+000 0.00000000e+000 4.66631809e-302]]


In [43]:
# Sau đó, thực hiện thêm 1 lần tích 1000 lần nữa:
k= 1000
for i in range(k-1):
    temp = temp.dot(C)
print(temp)

[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


##### 2.4. Ma trận Markov

In [45]:
M = np.array([ [0.8, 0.3], [0.2, 0.7]])
MM = M.dot(M) # tính M2, nghĩa là M2
print(MM) 

[[0.7  0.45]
 [0.3  0.55]]


In [46]:
MM = M.dot(M) # tính M3
print (MM) 

[[0.7  0.45]
 [0.3  0.55]]


In [47]:
for i in range(100): # tính các M^ khác
    MM = MM.dot(M)
print(MM)

[[0.6 0.6]
 [0.4 0.4]]


### 3. Phương trình ma trận

##### 3.2. Phân rã ma trận LU 

In [11]:
import numpy as np
from scipy import linalg
M = np.array([ [0.8, 0.3], [0.2, 0.7]])
P, L, U = linalg.lu(M) # lệnh lina.lu sẽ tách ma trận M thành 3 ma trận P, L và U
print (P)

[[1. 0.]
 [0. 1.]]


In [50]:
print(L)

[[1.   0.  ]
 [0.25 1.  ]]


In [52]:
print(U)

[[0.8   0.3  ]
 [0.    0.625]]


In [53]:
# Thử lại với phép nhân LU có bằng ma trận M ban đầu hay không:
L.dot(U) 

array([[0.8, 0.3],
       [0.2, 0.7]])

### 5. Bài toán ứng dụng 2 – Bài toán loan tin 

In [54]:
A = np.array([ [0,1,0,1],[0,0,1,0],[1,0,0,1],[1,1,0,0]])
temp = A.dot(A)
print(temp)

[[1 1 1 0]
 [1 0 0 1]
 [1 2 0 1]
 [0 1 1 1]]


In [55]:
temp = temp.dot(A)
print(temp) 

[[1 1 1 2]
 [1 2 0 1]
 [1 2 2 1]
 [2 1 1 1]]


In [59]:
# Sinh viên thực hành tính tổng các ∑ A^i:
A = np.array([ [0,1,0,1],[0,0,1,0],[1,0,0,1],[1,1,0,0]])
sumA = A
temp = A.dot(A)
k = 3
sumA = sumA + temp
for i in range(1, k-1):
    temp = temp.dot(A)
    sumA = sumA + temp
print(temp)

[[1 1 1 2]
 [1 2 0 1]
 [1 2 2 1]
 [2 1 1 1]]


In [60]:
print(sumA)

[[2 3 2 3]
 [2 2 1 2]
 [3 4 2 3]
 [3 3 2 2]]
